server:
  port: 8080
  servlet:
    display-name: BotApp
    context-path: "/botapp"

resources: src/main/resources
certs: certs
bot-config: ${resources}/bot-config.json

logging:
  file: ${resources}/logs/bot-app.log
  level:
    ROOT: INFO
    com.symphony.bdk.bot.sdk: DEBUG
    com.symphony.bdk.bot.template: DEBUG

samples:
  quote-command:
    quote-url: https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=USD&to_currency=%s&apikey=C7G0Q2QOJ80OECGM
